version: '3.8'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - mern-network

  frontend:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./my-react-app:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - mern-network


networks:
  mern-network:
    driver: bridge

