version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=2048
    env_file:
      - ./Backend/.env
    volumes:
      - backend_node_modules:/app/node_modules
    restart: unless-stopped
    networks:
      - mern-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  frontend:
    container_name: frontend
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
      args:
        VITE_APP_BACKEND_URL: https://www.techniverse25.rguktsklm.ac.in
        VITE_APP_KINDE_CLIENT_ID: b33e1744e75f47efba1e56f8f6956266
        VITE_APP_KINDE_ISSUER_URL: https://auth.techniverse25.rguktsklm.ac.in
        VITE_APP_KINDE_REDIRECT_URL: https://www.techniverse25.rguktsklm.ac.in/profile
        VITE_APP_KINDE_POST_LOGOUT_URL: https://www.techniverse25.rguktsklm.ac.in
    ports:
      - "5173:80"
    env_file:
      - ./my-react-app/.env
    volumes:
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:
