jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug AWS Credentials
        run: |
          # Debugging AWS Access Keys
          echo "AWS Access Key ID: ${AWS_ACCESS_KEY_ID}"  # Will show "undefined" if not set
          echo "AWS Secret Access Key: ${AWS_SECRET_ACCESS_KEY}"  # Will show "undefined" if not set
          echo "AWS Region: ${AWS_REGION}"

          # List AWS configuration to check credentials
          aws configure list || echo "AWS CLI configuration failed"

          # Test AWS identity to ensure credentials work
          aws sts get-caller-identity || echo "Failed to get identity, check AWS credentials and region."

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Configuration
        run: |
          aws sts get-caller-identity
          aws ec2 describe-instances --region ${{ secrets.AWS_REGION }} || echo "Failed to describe instances"
