name: Deploy to EC2

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        debug: true
        script: |
          # Cleanup
          echo "Performing cleanup..."
          docker system prune -af
          docker volume prune -f
          docker network prune -f
          docker builder prune -af --keep-storage 2GB
          docker rm -f $(docker ps -aq) 2>/dev/null || true
          docker rmi -f $(docker images -aq) 2>/dev/null || true
          
          # Navigate to project directory
          cd /home/ec2-user/Techniverse2k25 || exit 1

          # Create Backend/pem directory if it doesn't exist
          mkdir -p Backend/pem
          
          # Create PEM files from secrets
          echo "${{ secrets.HDFC_PUBLIC_KEY }}" > Backend/pem/public.pem
          echo "${{ secrets.HDFC_PRIVATE_KEY }}" > Backend/pem/privateKey.pem
          
          # Set permissions
          chmod 600 Backend/pem/*.pem
          

          # Update code
          echo "Fetching latest changes..."
          git fetch origin main
          git reset --hard origin/main
          git clean -fd
          
          # Deploy
          echo "Starting deployment...."
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1
          
          docker-compose -f docker-compose.prod.yml down --remove-orphans
          if docker-compose -f docker-compose.prod.yml build \
                --build-arg VITE_APP_BACKEND_URL=https://www.techniverse25.rguktsklm.ac.in \
                --build-arg VITE_APP_KINDE_CLIENT_ID=b33e1744e75f47efba1e56f8f6956266 \
                --build-arg VITE_APP_KINDE_ISSUER_URL=https://techniverse.kinde.com \
                --build-arg VITE_APP_KINDE_REDIRECT_URL=https://www.techniverse25.rguktsklm.ac.in/profile \
                --build-arg VITE_APP_KINDE_POST_LOGOUT_URL=https://www.techniverse25.rguktsklm.ac.in \
                --build-arg VITE_APP_API_BASE_URL=https://www.techniverse25.rguktsklm.ac.in/api \
                --no-cache; then
              echo "Build successful, starting containers..."
              docker-compose -f docker-compose.prod.yml up -d
          else 
              echo "Build failed!"
              exit 1
          fi
          
          sleep 15
          docker ps

    - name: Verify Deployment
      run: |
        sleep 30
        # Use HTTPS for verification
        curl -I https://techniverse25.rguktsklm.ac.in || echo "Frontend not responding.."
        curl -I https://techniverse25.rguktsklm.ac.in/api || echo "Backend not responding"